client/src/App.tsx
client/src/Router.tsx

feat: 라우터 구현

---

.prettierrc
client/config/webpack.config.common.js
client/package.json
client/src/Components/Header.tsx
client/src/Components/Menu.tsx
client/src/Pages/Login.tsx
client/src/Pages/Main.tsx
client/src/Pages/Signup.tsx
client/src/shared/styled.ts
client/src/styles/styled.d.ts
client/src/styles/theme.ts
client/yarn.lock

feat: css 수정

---

client/src/styles/styled.d.ts
client/src/styles/theme.ts

font 사이즈/웨이트 묶음 theme로 옮겼습니다.
적용은 이후 리팩토링 때..

update: globalStyle의 폰트 관련 theme로 이동

---

client/src/Components/Item.tsx
client/src/Pages/Main.tsx

feat: Item 러프하게 작성

---

client/src/App.tsx
client/src/Components/Header/Menu.tsx
client/src/Components/Header/Search.tsx
client/src/Components/Header/index.tsx
client/src/Pages/Main/index.tsx
client/src/shared/styled.ts
client/src/utils/node.ts

헤더 마크업 끝났슴돠~!
* 작업 내용
- 스마트레이어 (현재 마우스가 헤더를 벗어나도 select가 변경되지 않는데 추 후 논의후 수정하겠습니다~!)
- 검색 기록 저장 (max length 논의후 최근 n개 까지만 보이도록 수정 필요)

[FE] 헤더 마크업 완성

---

client/src/Components/Header/Menu.tsx
client/src/Pages/Category.tsx
client/src/Pages/Detail/Question.tsx
client/src/Pages/Detail/Review.tsx
client/src/Pages/Main/index.tsx
client/src/Pages/MyPage/Table.tsx
client/src/Pages/MyPage/index.tsx
client/src/shared/dummy.ts
client/yarn.lock

Refactor: dummy 데이터 한 곳으로 모음

---

client/src/Components/Button.tsx
client/src/Pages/Login.tsx

로그인페이지 목업 완료 했습니다 👍🏻 
나중에 라우터 손 좀 보고 리디렉션 + validation check도 진행해보겠습니다~!

[FE] 로그인 페이지 목업 완료

---

client/src/Router.tsx

[FE] 라우터 뒤로가기 적용

---

client/src/Pages/MyPage/Section.tsx
client/src/Pages/MyPage/Table.tsx
client/src/Pages/MyPage/tableTds.tsx

Table과 각 페이지(주로 마이페이지나 회원가입 같은?) 곳에서 section 생성 스타일을 통일하기 위한 컴포넌트 Section 추가했습니다.

Table / Section 컴포넌트

---

client/package.json
client/src/App.tsx
client/src/Components/Address/Popup.tsx
client/src/Components/Address/index.tsx
client/src/Pages/Signup.tsx
client/src/styles/styled.d.ts
client/src/styles/theme.ts

회원가입 또는 결제에 필요한 주소 검색창 컴포넌트를 구현했습니다.
* react-daum-postcode 라이브러리 사용을 하기때문에 시작 전에 yarn 설치 해주세요~!

feat: 주소 검색 및 입력 컴포넌트 구현

---

client/src/Components/Header/index.tsx
client/src/Components/Item.tsx
client/src/Components/SignatureLine.tsx
client/src/Pages/Detail/OptionBox.tsx
client/src/Pages/MyPage/Content/RecentOrderRow.tsx
client/src/Pages/MyPage/Content/Temp.tsx
client/src/Pages/MyPage/Content/index.tsx
client/src/Pages/MyPage/Section.tsx
client/src/Pages/MyPage/Sidebar/index.tsx
client/src/Pages/MyPage/Table/index.tsx
client/src/Pages/MyPage/Table/tableForm.tsx
client/src/Pages/MyPage/index.tsx
client/src/shared/dummy.ts
client/src/utils/util.ts

일단 라우터 없이 화면전환만 되게 해놨습니다. 
기타 수정 사항도 있습니다,

마이페이지 화면 전환 

---

.gitignore
server/.eslintrc.js
server/.gitignore
server/nest-cli.json
server/package.json
server/src/config/properties/properties.ts
server/src/core-module.ts
server/src/main.ts
server/src/user/application/auth-service.ts
server/src/user/domain/user.ts
server/src/user/dto/signin-request.ts
server/src/user/presentation/auth-controller.ts
server/src/user/user-module.ts
server/test/app.e2e-spec.ts
server/test/jest-e2e.json
server/tsconfig.build.json
tsconfig-server.json

- Nest.JS 서버 기본 셋팅
- 백엔드 구조를 DDD로 구축
- user 도메인에 ddd패턴을 사용하여 개발한 예시 코드 추가

[BE] 서버 기본 구조 구축

---

client/src/App.tsx
client/src/Components/Header/Menu.tsx
client/src/Components/Header/index.tsx
client/src/Components/Item.tsx
client/src/Pages/Login.tsx
client/src/Pages/Main/BannerSection/Banner.tsx
client/src/Pages/Main/GiftSection/Gift.tsx
client/src/Pages/Main/ReviewSection/ReviewList.tsx
client/src/Pages/MyPage/Sidebar/index.tsx
client/src/Pages/MyPage/Table/tableForm.tsx
client/src/Pages/Signup.tsx
client/src/Router.tsx

- ETLink 이름이 변경되었으니 사용하실 때 Link태그로 불러주세요~!

[FE] Refactor/router

---

client/package.json
client/src/Components/ModalWrapper/ModalWrapper.test.tsx
client/src/Components/ModalWrapper/index.tsx
client/src/Pages/Detail/Question/index.tsx
client/src/Pages/Detail/Review/index.tsx
client/src/Pages/Detail/index.tsx
client/src/Pages/Order/AddressModal/AddressModal.test.tsx
client/src/Pages/Order/AddressModal/index.tsx
client/src/Pages/Order/index.tsx
client/src/index.tsx
client/src/store/state.ts
client/yarn.lock

리코일 세팅하고 모달 관련 상태들을 전역으로 빼주었습니다.

chore: recoil setup

---

client/api/auth.ts
client/api/carts.ts
client/api/destinations.ts
client/api/my.ts
client/api/orders.ts
client/api/products.ts
client/api/questions.ts
client/api/reviews.ts
client/api/search.ts
client/api/users.ts
client/src/utils/axios.ts
client/yarn.lock

axios 관련 유틸 함수를 작성하고, api 호출 관련 함수들을 대략적으로 작성하였습니다.
- ({params})로 주는 게 좋을까요, 아니면 파라미터 값을 일일히 입력하도록 하고 호출시에 넣어주도록 하는 게 좋을까요?

chore: api 관련 setup

---

server/.eslintrc.js
server/package-lock.json
server/src/product/domain/products.ts
server/src/product/entity/product.ts

feat: DDD 구조 setup

---

server/src/destination/application/destination-service.ts
server/src/destination/domain/destinations.ts
server/src/destination/dto/destination-request.ts
server/src/destination/entity/destination.ts
server/src/destination/presentation/destination-controller.ts

destination domain 작성
- 코멘트 주시면 수정하여 다시 리뷰받도록 하겠습니다~

feat: destination domain 작성

---

server/src/destination/application/destination-service.ts
server/src/destination/entity/destination.ts
server/src/destination/presentation/destination-controller.ts
server/src/order/application/order-service.ts
server/src/order/domain/orders.ts
server/src/order/dto/order-request.ts
server/src/order/entity/order.ts
server/src/order/presentation/order-controller.ts

destination쪽을 조금 수정하고 order쪽을 작성하였습니다.
- 피드백 주시면 감사하겠습니당

feat: order domain 작성

---

client/src/Components/ModalWrapper/ModalWrapper.test.tsx
client/src/Components/ModalWrapper/index.tsx
client/src/Pages/Detail/Question/QuestionModal/QuestionModal.test.tsx
client/src/Pages/Detail/Question/index.tsx
client/src/Pages/Detail/Review/index.tsx
client/src/Pages/Order/AddressModal/AddressModal.test.tsx
client/src/Pages/Order/AddressModal/index.tsx
client/src/Pages/Order/index.tsx

모달 관련 state를 다시 컴포넌트 내부로 옮겼습니다.
- 슬퍼요,,

fix: modal 관련 이슈

---

server/src/cart/application/cart-service.ts
server/src/cart/domain/carts.ts
server/src/cart/dto/cart-request.ts
server/src/cart/entity/cart.ts
server/src/cart/presentation/cart-controller.ts

cart domain 관련하여 작성하였습니다.
- 당장 문제있어보이는 건 코멘트 달아주시면 수정하겠습니다! 코드 개선은 용성님 코드 참고하여 진행할게요ㅎㅎ

feat: cart domain 작성

---

server/src/cart/cart-module.ts
server/src/cart/entity/cart.ts
server/src/core-module.ts
server/src/destination/destination-module.ts
server/src/destination/entity/destination.ts
server/src/order/dto/order-request.ts
server/src/order/entity/order.ts
server/src/order/order-module.ts
server/src/order/presentation/order-controller.ts
server/src/product/entity/option.ts

cart/order/destination의 모듈을 작성하여 core-modules에 포함시켜주었습니다.
cart/order/destination의 엔티티에 createdAt/updatedAt을 추가해주었습니다.
- entity map으로 반환하는 건 이후에 수정하겠습니다~

feat: cart/order/destination module 작성

---

client/config/webpack.config.dev.js
server/package-lock.json
server/src/cart/application/cart-service.ts
server/src/cart/domain/carts.ts
server/src/cart/dto/cart-request.ts
server/src/cart/dto/cart-response.ts
server/src/cart/entity/cart.ts
server/src/cart/presentation/cart-controller.ts
server/src/destination/application/destination-service.ts
server/src/destination/domain/destinations.ts
server/src/destination/dto/destination-request.ts
server/src/destination/dto/destination-response.ts
server/src/destination/entity/destination.ts
server/src/destination/presentation/destination-controller.ts
server/src/order/domain/orders.ts
server/src/user/application/user-service.ts
server/src/user/dto/create-address.ts
server/yarn.lock

cart/destination에 대해 response를 class로 작성하고 api 코드를 조금 수정하였습니다.
- 컨플릭트.. 나지... 마라......

feat: cart/destination api 수정

---

server/package-lock.json
server/src/product/application/product-service.ts
server/src/product/domain/products.ts
server/src/product/dto/product-element-response.ts
server/src/product/dto/product-response.ts
server/src/product/dto/question-response.ts
server/src/product/dto/review-DTO.ts
server/src/product/dto/review-rate.ts
server/src/product/dto/review-response.ts
server/src/product/entity/option.ts
server/src/product/entity/product-detail-image.ts
server/src/product/entity/product-image.ts
server/src/product/entity/product.ts
server/src/product/presentation/product-controller.ts

feat: 엔티티 병합을 위한 중간 PR

---

server/src/cart/domain/carts.ts
server/src/cart/dto/cart-response.ts
server/src/destination/application/destination-service.ts
server/src/destination/domain/destinations.ts
server/src/destination/dto/destination-response.ts
server/src/order/application/order-service.ts
server/src/order/domain/orders.ts
server/src/order/dto/order-request.ts
server/src/order/dto/order-response.ts
server/src/order/entity/order.ts
server/src/order/presentation/order-controller.ts

cart/destination/order에 대한 api를 구현하였습니다.

feat: cart/destination/order api 구현 완료

---

server/src/core-module.ts
server/src/destination/application/destination-service.ts
server/src/destination/domain/destinations.ts
server/src/destination/dto/destination-request.ts
server/src/destination/presentation/destination-controller.ts
server/src/jwt-middleware.ts
server/src/user/application/auth-service.ts
server/src/user/application/user-service.ts
server/src/user/dto/create-address.ts

토큰을 검사하는 middleware를 만들었습니다 🙂 

[BE] 토큰 검사하는 middleware 생성

---

server/package-lock.json
server/package.json
server/src/config/properties/properties.ts
server/src/product/application/product-service.ts
server/src/product/domain/products.ts
server/src/product/dto/product-upload-request.ts
server/src/product/entity/product-image.ts
server/src/product/entity/product.ts
server/src/product/infrastructure/s3-repository.ts
server/src/product/presentation/product-controller.ts
server/src/product/product-module.ts

상품 등록이 가능하다;
S3를 이용하여 상품 이미지를 저장할 수 있다
- 예상시간: 1시간
- 걸린시간: 2시간 반 (엉뚱한 실수 때문임!)

feat: Upload product API

---

server/src/main.ts
server/src/product/application/product-service.ts

feat: cors setting

---

server/src/product/application/image-service.ts
server/src/product/application/product-service.ts
server/src/product/domain/products.ts
server/src/product/presentation/image-controller.ts
server/src/product/product-module.ts

feat: Image service

---

client/src/Components/ItemInfoBox/index.tsx
client/src/Pages/Cart/index.tsx
client/src/Pages/Detail/DetailInfo.tsx
client/src/Pages/Detail/OptionBox.tsx
client/src/Pages/Detail/index.tsx
client/src/Pages/Order/index.tsx
client/src/api/carts.ts
client/src/api/my.ts
client/src/shared/type.ts
client/src/utils/axios.ts
server/src/cart/application/cart-service.ts
server/src/cart/dto/cart-request.ts
server/src/cart/dto/cart-response.ts
server/src/cart/presentation/cart-controller.ts

상세페이지와 장바구니 관련 작업을 진행하였습니다.
- 살려주세요!

feat: detailPage & cartPage 데이터 매핑

---

client/package.json
client/src/App.tsx
client/src/Components/Header/index.tsx
client/src/Pages/Login/index.tsx
client/src/Pages/Signup/index.tsx
client/src/index.tsx
client/src/store/state.ts
client/src/utils/axios.ts
client/yarn.lock
server/src/jwt-middleware.ts
server/src/user/application/auth-service.ts
server/src/user/application/user-service.ts
server/src/user/presentation/auth-controller.ts
server/src/user/presentation/user-controller.ts

로그인, 회원가입, 로그아웃 구현
##실제 소요시간: 3H
다른 작업들 때문에 해당 작업 투입이 늦어 완료가 늦었습니다 ㅠ_ㅠ
+ 현재 에러 코드를 모두 같은 값으로 반환합니다. 추 후 케이스에 따라 다양한 코드를 반환하도록 하겠습니다.
+ 에러를 alert로 보여줘서 추 후 alert창 컴포넌트를 따로 만들어 표현을 하는게 좋을 것 같습니다.

로그인, 회원가입, 로그아웃 구현

---

server/src/order/domain/orders.ts
server/src/order/entity/order.ts
server/src/product/application/product-service.ts
server/src/product/domain/questions.ts
server/src/product/domain/reviews.ts
server/src/product/dto/question-request.ts
server/src/product/dto/review-DTO.ts
server/src/product/dto/review-my-response.ts
server/src/product/dto/review-request.ts
server/src/product/dto/review-response.ts
server/src/product/entity/review.ts
server/src/product/presentation/product-controller.ts
server/src/product/product-module.ts
server/src/user/application/my-service.ts
server/src/user/domain/users.ts
server/src/user/dto/my-reqeust.ts
server/src/user/dto/my-response.ts
server/src/user/entity/user.ts
server/src/user/presentation/my-controller.ts
server/src/user/user-module.ts

[ API ] my / reviews / questions 

---

server/src/product/dto/review-DTO.ts
server/src/product/dto/review-my-response.ts
server/src/product/dto/review-response.ts
server/src/product/entity/review.ts

review entity에 생성날짜를 빼먹어서 추가했습니다. 
- (특이 사항 1)
- (특이 사항 2)

feat: review createAt 추가

---

client/src/App.tsx
client/src/Pages/Order/index.tsx
client/src/Pages/OrderSuccess.tsx
client/src/api/payment.ts
client/src/utils/axios.ts
server/package-lock.json
server/package.json
server/src/core-module.ts
server/src/payment/payment-module.ts
server/src/payment/presentation/payment-controller.ts

카카오페이 연동 완료
`카카오페이` 클릭시
리다이렉션 url
- success 페이지는 추후 마크업 작업 하겠습니다.
- tid가 그냥 나와있는데, 나중에 private으로 넣도록 하겠습니다.

feat: 카카오페이 연동

---

client/src/Pages/Detail/OptionBox.tsx
client/src/Pages/Order/AddressForm.tsx
client/src/api/carts.ts
client/src/api/destinations.ts
server/src/cart/presentation/cart-controller.ts
server/src/destination/dto/destination-request.ts
server/src/destination/presentation/destination-controller.ts
server/src/jwt-middleware.ts
server/src/order/presentation/order-controller.ts
server/src/user/application/user-service.ts
server/src/user/dto/create-address.ts
server/src/user/presentation/my-controller.ts

미들웨어 변경에 따라 기존 param으로 받아오던 useId를 body에서 받아오도록 수정하였고,  
그에 따른 dto 및 api 호출 로직을 수정하였습니다.
- userId와 관련된 에러 핸들링 로직을 같이 생각해보면 좋을 것  같습니다!

feat: api param/body 수정

---

server/src/order/dto/order-response.ts
server/src/order/entity/order.ts
server/src/product/dto/question-response.ts
server/src/product/dto/review-my-response.ts
server/src/product/dto/review-response.ts
server/src/product/entity/product.ts
server/src/product/entity/question.ts
server/src/product/entity/review.ts
server/src/user/application/my-service.ts
server/src/user/domain/wishes.ts
server/src/user/dto/my-response.ts
server/src/user/entity/user.ts
server/src/user/entity/wish.ts
server/src/user/presentation/my-controller.ts
server/src/user/user-module.ts

Wish 관련 API 추가하면서 관련해서 문제사항(foreign key 등..) 수정했습니다. 
- 커밋로그 확인. (오타.. Review => Wish)
- (특이 사항 1)
- (특이 사항 2)

Wish api 추가 및 관련 API 수정

---

client/src/Pages/Login/LoginSection/index.tsx
client/src/Pages/Login/OAuthLoginSection/index.tsx
client/src/Pages/Order/index.tsx
client/src/config/properties.ts
client/src/utils/axios.ts

배포환경에서 환경변수가 제대로 안들어가서 따로 properties.ts를 만들었습니다.

[FE] 환경변수 properties 파일 설정

---

client/src/App.tsx
client/src/Components/ImageHoverWrapper/index.tsx
client/src/Components/Item/index.tsx
client/src/Components/ToggleImageWrapper/index.tsx
client/src/Pages/Detail/Review/ReviewBox/ReviewBox.test.tsx
client/src/Pages/Detail/Review/ReviewBox/index.tsx
client/src/Pages/Main/ReviewSection/ReviewList/ReviewList.test.tsx
client/src/Pages/MyPage/ContentArea/contents/Question/index.tsx
client/src/Pages/MyPage/ContentArea/contents/Review/index.tsx
client/src/Pages/MyPage/ContentArea/contents/WishList/index.tsx
client/src/Pages/MyPage/Table/rows/Review/Review.test.tsx
client/src/Pages/MyPage/index.tsx
client/src/api/my.ts
client/src/assets/wish.svg
client/src/shared/dummy.ts
client/src/shared/type.ts
client/src/styles/theme.ts
server/src/product/domain/questions.ts
server/src/product/domain/reviews.ts
server/src/product/dto/question-response.ts
server/src/product/dto/review-my-response.ts
server/src/user/application/my-service.ts
server/src/user/domain/wishes.ts
server/src/user/dto/my-response.ts
server/src/user/presentation/my-controller.ts

리뷰, 문의, 찜목록 등 마이페이지 API 작업들입니다. 
- (특이 사항 1)
- (특이 사항 2)

MyPage 관련 API 수정 / 클라이언트 연결

---

server/src/user/application/my-service.ts
server/src/user/domain/wishes.ts
server/src/user/dto/my-response.ts
server/src/user/presentation/my-controller.ts

빼먹은거 추가! 
- (특이 사항 1)
- (특이 사항 2)

my info 빼먹은 email 추가

---

client/src/Components/Checkbox/index.tsx
client/src/Pages/Cart/index.tsx
client/src/Pages/Order/AddressBox/AddressBox.test.tsx
client/src/Pages/Order/AddressBox/index.tsx
client/src/Pages/Order/AddressModal/index.tsx
client/src/Pages/Order/index.tsx
client/src/api/destinations.ts
client/src/api/orders.ts
client/src/shared/type.ts
client/src/styles/theme.ts
server/src/cart/application/cart-service.ts
server/src/cart/presentation/cart-controller.ts
server/src/destination/application/destination-service.ts
server/src/destination/domain/destinations.ts
server/src/destination/presentation/destination-controller.ts
server/src/order/application/order-service.ts
server/src/order/presentation/order-controller.ts
server/src/payment/presentation/payment-controller.ts

주문/결제 관련된 구현을 완료하였습니다.
- 이상한 부분 있으면 코멘트 남겨주세요!

feat: 주문/결제 구현 완료

---

client/src/App.tsx
client/src/Components/Header/Search/DropDown/AutoCompleteList/index.tsx
client/src/Components/Header/Search/index.tsx
client/src/Components/ProductList/index.tsx
client/src/Pages/Category/index.tsx
client/src/Pages/Main/BannerSection/Banner/index.tsx
client/src/Pages/Main/ProductSection/index.tsx
client/src/Pages/MyPage/ContentArea/contents/Root/index.tsx
client/src/Pages/MyPage/ContentArea/contents/WishList/index.tsx
client/src/Pages/Search/index.tsx
client/src/api/search.ts
client/src/hooks/useDebounce.ts
client/src/shared/styled.ts
client/src/shared/type.ts
server/src/config/messages.ts
server/src/product/application/product-service.ts
server/src/product/application/search-service.ts
server/src/product/domain/products.ts
server/src/product/dto/product-search-response.ts
server/src/product/presentation/image-controller.ts
server/src/product/presentation/product-controller.ts
server/src/product/product-module.ts

검색 페이지를 시작하기 위한 기초 보수공사를 마쳤습니다.
- 영준님 엔티티 수정하신거 PR날려주세효...

[FE, BE] Elastic Search 자동완성, 검색 구현 기초작업 완료

---

client/src/Components/Header/Menu/index.tsx
client/src/Components/Header/Search/index.tsx
client/src/Components/Header/index.tsx
client/src/Components/Input/ValidationInput/index.tsx
client/src/Components/Item/index.tsx
client/src/Components/ProductList/index.tsx
client/src/Pages/Category/Banner/index.tsx
client/src/Pages/Category/Filter/index.tsx
client/src/Pages/Category/index.tsx
client/src/Pages/Detail/Review/ReviewBox/index.tsx
client/src/Pages/Detail/index.tsx
client/src/Pages/Main/BannerSection/Banner/index.tsx
client/src/Pages/Main/GiftSection/GiftList/index.tsx
client/src/Pages/Main/ReviewSection/ReviewList/index.tsx
client/src/Pages/Main/ReviewSection/index.tsx
client/src/Pages/MyPage/ContentArea/contents/Wishes/WistList.test.tsx
client/src/shared/dummy.ts
client/src/shared/styled.ts
client/src/styles/theme.ts

메인, 헤더, 카테고리, 검색 반응형 제작 + 카테고리 목업

[FE] 헤더 목업 + 반응형 구현

---

client/src/Components/Address/index.tsx
client/src/Components/CartOrderBox/index.tsx
client/src/Components/Footer/index.tsx
client/src/Components/Header/Search/index.tsx
client/src/Components/Header/index.tsx
client/src/Components/Input/InputSection/index.tsx
client/src/Components/Input/ValidationInput/index.tsx
client/src/Components/Input/index.tsx
client/src/Components/ItemInfoBox/index.tsx
client/src/Pages/Cart/index.tsx
client/src/Pages/Detail/OptionBox.tsx
client/src/Pages/Detail/Question/QuestionModal/index.tsx
client/src/Pages/Detail/Review/ReviewModal/index.tsx
client/src/Pages/Login/LoginSection/index.tsx
client/src/Pages/Login/index.tsx
client/src/Pages/Order/index.tsx
client/src/api/orders.ts
client/src/styles/global-style.ts

feat: 장바구니/주문결제 반응형 적용

---

client/src/Components/ItemInfoBox/index.tsx
client/src/Pages/Detail/Question/QuestionBox/index.tsx
client/src/Pages/Detail/Question/QuestionModal/QuestionModal.test.tsx
client/src/Pages/Detail/Question/index.tsx
client/src/Pages/MyPage/ContentArea/ContentArea.test.tsx
client/src/Pages/MyPage/ContentArea/contents/Order/OrderBox.tsx
client/src/Pages/MyPage/ContentArea/contents/Question/index.tsx
client/src/styles/global-style.ts

chore: question 리디자인 진행 중 공유

---

client/src/Components/Button/index.tsx
client/src/Components/CartOrderBox/index.tsx
client/src/Components/ItemInfoBox/index.tsx
client/src/Pages/Cart/index.tsx
client/src/Pages/Detail/DetailInfo.tsx
client/src/Pages/Detail/OptionBox.tsx
client/src/Pages/Detail/Question/QuestionBox/index.tsx
client/src/Pages/Detail/Question/index.tsx
client/src/Pages/Detail/Review/index.tsx
client/src/Pages/Detail/index.tsx
client/src/Pages/Order/index.tsx
client/src/api/questions.ts
client/src/styles/global-style.ts
client/src/styles/theme.ts

feat: detailPage css 수정 및 반응형 적용

---

server/src/product/domain/reviews.ts

메인페이지의 리뷰를 이미지 있고, 5점이며, 가장 최신인 3개를 불러오도록 했슴동 
- (특이 사항 1)
- (특이 사항 2)

메인페이지 리뷰 최신/이미지/별5점만

---

client/src/Pages/Detail/index.tsx
client/src/Pages/Main/ProductSection/index.tsx
server/src/product/dto/product-element-response.ts
server/src/product/dto/product-response.ts
server/src/user/entity/wish.ts

wish 관련 진행 중 공유 

---

client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
client/src/Pages/Order/AddressBox/index.tsx
client/src/Pages/Order/OrderContent/LoggedinContent.tsx
client/src/Pages/OrderResult/index.tsx
client/src/api/my.ts
server/package-lock.json
server/package.json
server/src/user/application/my-service.ts
server/src/user/domain/users.ts
server/src/user/dto/my-reqeust.ts
server/src/user/presentation/my-controller.ts

feat: myPage 내 정보 수정 구현

---

client/src/Components/ItemInfoBox/CartSelects.tsx
client/src/Components/ItemInfoBox/index.tsx
client/src/Components/NumInput/index.tsx
client/src/Pages/Detail/OptionBox.tsx
client/src/styles/global-style.ts

fix: 수량 numInput 수정 #182

---

client/src/Components/Footer/index.tsx
client/src/Pages/Detail/Review/ReviewBox/ReviewBox.test.tsx
client/src/Pages/Detail/Review/ReviewBox/index.tsx
client/src/Pages/Detail/Review/ReviewCard/index.tsx
client/src/Pages/Main/ProductSection/index.tsx
client/src/shared/dummy.ts
client/src/shared/type.ts
server/src/user/presentation/my-controller.ts

feat: review box/card 수정, footer 수정

---

client/src/Components/Common/NoData/index.tsx
client/src/Components/Item/index.tsx
client/src/Components/ReviewBox/index.tsx
client/src/Pages/Main/index.tsx
client/src/Pages/MyPage/ContentArea/contents/Order/OrderBox.tsx
client/src/Pages/MyPage/ContentArea/contents/Order/index.tsx
client/src/Pages/MyPage/ContentArea/contents/Order/mobile/MobileOrderContainer.tsx
client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
client/src/Pages/MyPage/Nav/index.tsx
client/src/Pages/MyPage/index.tsx

메인페이지 반응형과 
모바일 화면에서 페이지 우측에 공간 생겨서 깨지는 문제 찾아서 해결했습니다
혹시 못 발견한 부분 있으면 말씀해주세요 
- (특이 사항 1)
- (특이 사항 2)

메인페이지 반응형 / 모바일에 우측에 공간 생기는 문제 해결

---

client/src/Pages/Detail/OptionBox.tsx
client/src/api/reviews.ts
server/src/cart/application/cart-service.ts
server/src/config/messages.ts
server/src/destination/application/destination-service.ts
server/src/order/application/order-service.ts
server/src/product/application/question-service.ts
server/src/product/application/review-service.ts
server/src/product/domain/reviews.ts

cart/destination/order/review/question 서비스에서 에러 헨들링 처리 완료

refactor: cart/destination/order/review/question service error handling

---

client/src/api/search.ts
server/src/product/presentation/product-controller.ts

[FIX] 자동완성 api를 파라미터에서 쿼리로 변경
배포용 서버에서 안돼서 지금 핫픽스중입니다..!

[FIX] 자동완성 api를 파라미터에서 쿼리로 변경

---

server/package-lock.json
server/src/config/messages.ts
server/src/product/application/product-service.ts
server/src/product/application/search-service.ts

feat: elasticsearch delete index method

---

client/src/Components/Item/index.tsx
client/src/Pages/Detail/OptionBox.tsx
client/src/Pages/Detail/index.tsx
client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
client/src/api/my.ts
client/src/shared/type.ts
server/src/cart/application/cart-service.ts
server/src/config/messages.ts
server/src/product/application/product-service.ts
server/src/product/application/question-service.ts
server/src/user/application/my-service.ts
server/src/user/presentation/my-controller.ts

서버에서 에러 핸들링 처리 추가했고
디테일 페이지에서 wish 버튼 관련해서 발생하던 에러를 해결했습니다.
디바운스 훅과 react-query가 구조상 충돌이 있는 거 같습니다.
이전에는 클릭을 하지 않아도 디바운스 값이 변경됨을 인지해서 요청을 보냈기에 클릭 상태를 따로 관리했습니다.
실제로는 디바운스 훅에서 해당 이벤트에 따라 동작하도록 개선해야할 듯.. 
- (특이 사항 1)
- (특이 사항 2)

fix: 에러핸들링 / Wish 에러 해결

---

server/package-lock.json
server/src/product/domain/products.ts

feat: product order sorting

---

client/src/Components/Footer/index.tsx
client/src/Components/ReviewBox/index.tsx
client/src/Pages/Category/index.tsx
client/src/Pages/Detail/Question/QuestionBox/index.tsx
client/src/Pages/Detail/Review/Progress/index.tsx
client/src/Pages/Detail/index.tsx
client/src/Pages/Main/index.tsx
client/src/shared/styled.ts
client/src/shared/type.ts
server/src/product/application/question-service.ts
server/src/product/dto/product-response.ts

fix: detail/pagewrapper/banner 반응형 버그픽스

---

client/src/Pages/Detail/index.tsx

fix: detailPage 반응형 수정

---

server/src/cart/application/cart-service.ts
server/src/config/filter/exception-handler.ts
server/src/destination/application/destination-service.ts
server/src/main.ts
server/src/order/application/order-service.ts
server/src/product/application/image-service.ts
server/src/product/application/product-service.ts
server/src/product/application/question-service.ts
server/src/product/application/review-service.ts
server/src/product/application/search-service.ts
server/src/product/presentation/product-controller.ts
server/src/user/application/auth-service.ts
server/src/user/application/my-service.ts
server/src/user/application/user-service.ts
server/src/user/presentation/auth-controller.ts
server/src/user/presentation/my-controller.ts
server/src/user/presentation/user-controller.ts

feat: apply exception filter

---

client/src/Components/ImageHoverWrapper/index.tsx
client/src/Components/Item/index.tsx
client/src/Components/ProductList/index.tsx
client/src/Pages/Detail/index.tsx
client/src/Pages/Main/BannerSection/Banner/index.tsx
client/src/Pages/Main/BannerSection/Carousel/index.tsx
client/src/Pages/Main/ReviewSection/ReviewCard/index.tsx
client/src/Pages/Main/ReviewSection/ReviewList/index.tsx
client/src/Pages/Main/ReviewSection/index.tsx
client/src/Pages/Main/index.tsx

반응형 마무리 완료!
- (특이 사항 1)
- (특이 사항 2)

메인페이지 반응형 

---

server/src/product/application/product-service.ts
server/src/product/domain/products.ts
server/src/product/entity/product.ts

feat: add wishLength column in product

---

server/src/user/domain/wishes.ts
server/src/user/entity/wish.ts

(작업 내역 한줄로 요약)
(작업 내역 확인하기 편하도록 gif 첨부)
- (특이 사항 1)
- (특이 사항 2)

feat: 마이페이지 wish 오류 수정

---

client/src/Pages/Admin/Home/index.tsx
client/src/Pages/Admin/Home/styles/index.ts
server/src/user/domain/wishes.ts

feat: wish logic

---

client/src/App.tsx
client/src/Components/Common/Alert/index.tsx
client/src/Components/ItemInfoBox/CartSelects.tsx
client/src/Components/ItemInfoBox/index.tsx
client/src/Pages/MyPage/ContentArea/contents/UserInfo/index.tsx
client/src/Pages/Order/index.tsx

feat: 반응형 수정 및 카카오페이 결제 금액 제한

---

client/src/App.tsx
client/src/Components/ProductList/InfiniteScroll/index.tsx
client/src/Pages/MyPage/index.tsx
client/src/Router.tsx

잘못된 URL 요청 시, 페이지를 404로 리디렉션 시켜주는 기능을 구현했습니다.
- URL이 잘 못 입력되는 상황은 최초 진입 시 밖에 없으므로 useEffect에서 체크 하도록 했습니다!

[FE] Redirect Pages

---

client/src/Components/Common/Button/APIButton/index.tsx
client/src/Pages/Detail/Question/QuestionModal/index.tsx
client/src/Pages/Detail/Review/ReviewModal/index.tsx
client/src/Pages/Login/LoginSection/index.tsx
client/src/Pages/Login/OAuthLoginSection/index.tsx
client/src/Pages/Login/index.tsx
client/src/Pages/Signup/index.tsx

[FIX] API button

---

client/src/Components/Item/index.tsx
client/src/Pages/Main/ProductSection/index.tsx
client/src/Pages/Main/index.tsx
client/src/styles/theme.ts

(작업 내역 한줄로 요약)
(작업 내역 확인하기 편하도록 gif 첨부)
- (특이 사항 1)
- (특이 사항 2)

fix: 사소한 css 수정

---

client/src/Components/Item/index.tsx
client/src/Components/ProductList/InfiniteScroll/index.tsx
client/src/Components/ProductList/index.tsx
client/src/Pages/Detail/OptionBox.tsx
client/src/Pages/Detail/index.tsx
client/src/Pages/MyPage/ContentArea/contents/Order/OrderContainer.tsx
client/src/Pages/MyPage/ContentArea/contents/Wish/index.tsx
client/src/shared/dummy.ts
client/src/shared/type.ts
server/src/config/filter/exception-handler.ts
server/src/product/domain/products.ts
server/src/product/dto/product-element-response.ts
server/src/product/entity/product.ts
server/src/user/application/auth-service.ts
server/src/user/application/my-service.ts
server/src/user/domain/wishes.ts
server/src/user/dto/my-response.ts

최종 데모를 위한 각종 처리들 
PR제목 참고 
- (특이 사항 1)
- (특이 사항 2)

Tags 추가 / 메인, 카테고리 반응형 / 품절 관련 추가 / 에러핸들러 개선 

---

client/src/Pages/MyPage/ContentArea/contents/Order/OrderBox.tsx
client/src/Pages/MyPage/ContentArea/contents/Order/OrderContainer.tsx
client/src/Pages/MyPage/ContentArea/contents/Order/index.tsx
client/src/api/my.ts
server/src/config/messages.ts
server/src/order/domain/orders.ts
server/src/user/application/my-service.ts
server/src/user/presentation/my-controller.ts

주문 취소 기능 추가 완료! 
- (특이 사항 1)
- (특이 사항 2)

주문 취소 기능 추가 

---

client/src/Components/ProductList/InfiniteScroll/index.tsx
server/src/product/domain/products.ts

무한 스크롤에서 중간에 잘못 고쳐서 발생한 버그에 대해 수정을 했습니다 🙂

[FE] 무한 스크롤 수정

---

client/src/Pages/Main/BannerSection/Carousel/index.tsx
client/src/Pages/Main/GiftSection/index.tsx
client/src/Pages/Main/ProductSection/index.tsx
client/src/Pages/Main/ReviewSection/index.tsx
client/src/Pages/Main/index.tsx
client/src/shared/dummy.ts

전체 카테고리 글자 색상이 흰색이어서 안보였던 거 검정으로 변경했습니다!
+ 메인페이지 섹션을 div에서 section 태그로 변경했습니다 🙂

[FE] 메인페이지 시맨틱 + 전체 카테고리 폰트 색상 변경

---

client/src/Components/ProductList/InfiniteScroll/index.tsx
client/src/Pages/Category/index.tsx
client/src/Pages/Search/index.tsx

무한스크롤 관련해서 리랜더링을 일으키는 상태를 최소화하고 react Query를 사용하는 것으로 바꾸었습니다 🙂
- 이줴 진짜 끝~!

[FIX] 무한스크롤 관련 버그 수정!

---

server/src/product/application/search-service.ts
server/src/product/presentation/product-controller.ts

검색관련 찜하기 / 최대수 핫픽스 
- (특이 사항 1)
- (특이 사항 2)

hotfix 서치 관련 

---

server/src/order/application/order-service.ts
server/src/order/order-module.ts
server/src/product/application/product-service.ts
server/src/product/domain/products.ts
server/src/product/product-module.ts

(작업 내역 한줄로 요약)
(작업 내역 확인하기 편하도록 gif 첨부)
- (특이 사항 1)
- (특이 사항 2)

feat: order 생성시 product/option stock 업데이트

---

client/src/Components/Item/index.tsx

(작업 내역 한줄로 요약)
(작업 내역 확인하기 편하도록 gif 첨부)
- (특이 사항 1)
- (특이 사항 2)

chore: 품절 박스 border-radius
